<?php

use Illuminate\Database\Seeder;

class FacturasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('facturas')->delete();
        
        \DB::table('facturas')->insert(array (
            0 => 
            array (
                'id' => 1,
                'num_factura' => 5005946,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Maria Solorzano',
                'fecha_nacimiento' => '1987-01-01 00:00:00',
                'edad' => '30 A',
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CENTRO MEDICO CARRAS',
                'medico' => 'Dr. Rommel Carrasco',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-20 10:03:36',
                'updated_at' => '2017-05-20 10:08:03',
            ),
            1 => 
            array (
                'id' => 2,
                'num_factura' => 5005945,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Lourdes Zambrano',
                'fecha_nacimiento' => '1953-01-01 00:00:00',
                'edad' => '64 A',
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'H.M.C Laboratorio',
                'medico' => 'Dr. Roberto Figueroa',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-20 10:03:43',
                'updated_at' => '2017-05-20 10:24:57',
            ),
            2 => 
            array (
                'id' => 3,
                'num_factura' => 5005944,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Maria Carranza',
                'fecha_nacimiento' => '1983-01-01 00:00:00',
                'edad' => '34 A',
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'POLICLINICA',
                'medico' => 'Dr. Elmer Turcios',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-20 10:04:30',
                'updated_at' => '2017-05-20 10:11:31',
            ),
            3 => 
            array (
                'id' => 4,
                'num_factura' => 5005947,
                'num_cedula' => '0801198309421',
                'nombre_completo_cliente' => 'Erick Harry Paz',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47 A',
                'correo' => 'dartreck@gmail.com',
                'correo2' => 'dartreck@gmail.com',
                'direccion_entrega_sede' => 'Clinicas Viera',
                'medico' => 'Dra. Heike Hesse',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-20 10:55:10',
                'updated_at' => '2017-05-23 09:24:02',
            ),
            4 => 
            array (
                'id' => 5,
                'num_factura' => 5005949,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Maria  Adela  Izaguirre  Reina',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47 A',
                'correo' => 'lagosmaria2010@gmail.com',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'MEDICAL CENTER CLINI',
                'medico' => 'Dr. Carlos Armando Ramos',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-20 10:55:51',
                'updated_at' => '2017-05-23 08:41:37',
            ),
            5 => 
            array (
                'id' => 6,
                'num_factura' => 5005950,
                'num_cedula' => '1801198615271',
                'nombre_completo_cliente' => 'Aaron Gerardo Reaños Aguilera',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47 A',
                'correo' => 'ing_aaronr@unitec.edu',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'HOSPITAL MILITAR',
                'medico' => 'Dra. Patricia Giron',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-20 10:56:08',
                'updated_at' => '2017-06-03 11:20:34',
            ),
            6 => 
            array (
                'id' => 7,
                'num_factura' => 5005948,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Fabiola  Maria Fernandez Echeverria',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47 A',
                'correo' => 'fabiolafdeze@hotmail.com',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CLINILAB',
                'medico' => 'Dr. Edwin Padilla',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-20 10:56:21',
                'updated_at' => '2017-06-03 12:26:57',
            ),
            7 => 
            array (
                'id' => 8,
                'num_factura' => 5005951,
                'num_cedula' => '1512192600019',
                'nombre_completo_cliente' => 'Santos Roque Ortiz',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47',
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CENTRO MEDICO CARRAS',
                'medico' => 'Dra. Ligia Fu Carrasco',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-20 10:57:55',
                'updated_at' => '2017-05-20 10:57:55',
            ),
            8 => 
            array (
                'id' => 9,
                'num_factura' => 5005952,
                'num_cedula' => '1701194300207',
                'nombre_completo_cliente' => 'Graciela Garcia Villalobos',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47',
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => NULL,
                'medico' => 'Dr. Juan Jose Flores',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-20 10:58:36',
                'updated_at' => '2017-05-20 10:58:36',
            ),
            9 => 
            array (
                'id' => 10,
                'num_factura' => 5005953,
                'num_cedula' => '0801199507445',
                'nombre_completo_cliente' => 'Abel  Jamil Azar Palma',
                'fecha_nacimiento' => '1995-12-04 00:00:00',
                'edad' => '21 A',
                'correo' => 'abeljamil95@gmail.com',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Clinicas Viera',
                'medico' => 'Dra. Heike Hesse',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-20 11:00:58',
                'updated_at' => '2017-06-03 10:55:58',
            ),
            10 => 
            array (
                'id' => 11,
                'num_factura' => 5005954,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Jose  Abraham  Moya  Santos',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47',
                'correo' => 'bram.moya@yahoo.com',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Correo y Env.RD',
                'medico' => 'Dra. Heike Hesse',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-20 11:04:27',
                'updated_at' => '2017-05-20 11:04:27',
            ),
            11 => 
            array (
                'id' => 12,
                'num_factura' => 5005955,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Martha Gonzalez Rosales',
                'fecha_nacimiento' => '1953-01-01 00:00:00',
                'edad' => '34 A',
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CL. SAN JORGE',
                'medico' => 'Dr. George Frazer',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-20 11:58:51',
                'updated_at' => '2017-06-03 10:29:37',
            ),
            12 => 
            array (
                'id' => 13,
                'num_factura' => 5005956,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Martha Gonzalez Rosales',
                'fecha_nacimiento' => '1983-01-01 00:00:00',
                'edad' => '34 A',
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CL. SAN JORGE',
                'medico' => 'Dr. George Frazer',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-20 11:59:42',
                'updated_at' => '2017-05-22 12:24:23',
            ),
            13 => 
            array (
                'id' => 14,
                'num_factura' => 5005957,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Carmen Cruz',
                'fecha_nacimiento' => '1982-01-01 00:00:00',
                'edad' => '47',
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'HOSPITAL MILITAR',
                'medico' => 'Dra, Teresa Andara',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-20 12:00:41',
                'updated_at' => '2017-05-20 12:00:41',
            ),
            14 => 
            array (
                'id' => 15,
                'num_factura' => 5005958,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Darwin Perez',
                'fecha_nacimiento' => '1973-01-01 00:00:00',
                'edad' => '47',
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'SAN PEDRO SULA',
                'medico' => 'Dr. Ruben Lopez Canales',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-20 12:02:25',
                'updated_at' => '2017-05-20 12:02:25',
            ),
            15 => 
            array (
                'id' => 16,
                'num_factura' => 5005959,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Luis Arevalo',
                'fecha_nacimiento' => '1982-01-01 00:00:00',
                'edad' => '35 A',
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CENTRO MEDICO LA ESP.',
                'medico' => 'Dr. Sorto',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-20 12:03:23',
                'updated_at' => '2017-06-03 11:27:11',
            ),
            16 => 
            array (
                'id' => 17,
                'num_factura' => 5005961,
                'num_cedula' => '0801198813342',
                'nombre_completo_cliente' => 'Edith Marisol Alvarez Mena',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47 A',
                'correo' => 'edith.m.mena@gmail.com',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'HOSPITAL MILITAR',
                'medico' => NULL,
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-23 09:25:43',
                'updated_at' => '2017-06-03 12:22:13',
            ),
            17 => 
            array (
                'id' => 18,
                'num_factura' => 5005963,
                'num_cedula' => '0801198813342',
                'nombre_completo_cliente' => 'Abel  Jamil Azar Palma',
                'fecha_nacimiento' => '1988-06-23 18:00:00',
                'edad' => '21 A',
                'correo' => 'abeljamil95@gmail.com',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Clinicas Viera',
                'medico' => 'Dra. Heike Hesse',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-23 09:33:23',
                'updated_at' => '2017-06-03 12:28:31',
            ),
            18 => 
            array (
                'id' => 19,
                'num_factura' => 5005932,
                'num_cedula' => '0311198100309',
                'nombre_completo_cliente' => 'Juan Jorge Mourra Carias',
                'fecha_nacimiento' => '1972-05-11 00:00:00',
                'edad' => '47',
                'correo' => 'jmourra@bcie.org',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Correo y Env.RD',
                'medico' => 'Dra. Claudia Mejia',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-27 18:14:25',
                'updated_at' => '2017-05-27 18:14:25',
            ),
            19 => 
            array (
                'id' => 20,
                'num_factura' => 5005933,
                'num_cedula' => '0311198100309',
                'nombre_completo_cliente' => 'Juan Jorge Mourra Carias',
                'fecha_nacimiento' => '1972-05-11 00:00:00',
                'edad' => '45 A',
                'correo' => 'jmourra@bcie.org',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Correo y Env.RD',
                'medico' => 'Dr. Luis Fernando Flores',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-27 18:37:57',
                'updated_at' => '2017-06-03 12:10:38',
            ),
            20 => 
            array (
                'id' => 21,
                'num_factura' => 5005937,
                'num_cedula' => '0801198309421',
                'nombre_completo_cliente' => 'Erick Harry Paz Torres',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47',
                'correo' => 'dartreck@gmail.com',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Clinicas Viera',
                'medico' => 'Dra. Heike Hesse',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-27 18:37:57',
                'updated_at' => '2017-05-27 18:37:57',
            ),
            21 => 
            array (
                'id' => 22,
                'num_factura' => 5005938,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Fabiola  Maria Fernandez Echeverria',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47',
                'correo' => 'fabiolafdeze@hotmail.com',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CLINILAB',
                'medico' => 'Dr. Edwin Padilla',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-27 18:37:58',
                'updated_at' => '2017-05-27 18:37:58',
            ),
            22 => 
            array (
                'id' => 23,
                'num_factura' => 5005939,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Fabiola  Maria Fernandez Echeverria',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47 A',
                'correo' => 'fabiolafdeze@hotmail.com',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CLINILAB',
                'medico' => 'Dr. Edwin Padilla',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-05-27 18:37:58',
                'updated_at' => '2017-06-03 11:15:00',
            ),
            23 => 
            array (
                'id' => 24,
                'num_factura' => 5005936,
                'num_cedula' => '0311198100309',
                'nombre_completo_cliente' => 'Juan Jorge Mourra Carias',
                'fecha_nacimiento' => '1972-05-11 00:00:00',
                'edad' => '47',
                'correo' => 'jmourra@bcie.org',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Correo y Env.RD',
                'medico' => 'Dr. Luis Fernando Flores',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-27 18:37:58',
                'updated_at' => '2017-05-27 18:37:58',
            ),
            24 => 
            array (
                'id' => 25,
                'num_factura' => 5005940,
                'num_cedula' => '0311198100309',
                'nombre_completo_cliente' => 'Juan Jorge Mourra Carias',
                'fecha_nacimiento' => '1972-05-11 00:00:00',
                'edad' => '45 A',
                'correo' => 'jmourra@bcie.org',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Correo y Env.RD',
                'medico' => 'Dr. Luis Fernando Flores',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-27 18:37:58',
                'updated_at' => '2017-06-03 11:31:53',
            ),
            25 => 
            array (
                'id' => 26,
                'num_factura' => 5005942,
                'num_cedula' => '0311198100309',
                'nombre_completo_cliente' => 'Juan Jorge Mourra Carias',
                'fecha_nacimiento' => '1972-05-11 00:00:00',
                'edad' => '45 A',
                'correo' => 'jmourra@bcie.org',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Correo y Env.RD',
                'medico' => 'Dra. Claudia Mejia',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-27 18:37:58',
                'updated_at' => '2017-06-03 10:54:26',
            ),
            26 => 
            array (
                'id' => 27,
                'num_factura' => 5005943,
                'num_cedula' => '0801198309421',
                'nombre_completo_cliente' => 'Erick Harry Paz Torres',
                'fecha_nacimiento' => '1969-12-31 18:00:00',
                'edad' => '47',
                'correo' => 'dartreck@gmail.com',
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Clinicas Viera',
                'medico' => 'Dra. Heike Hesse',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-05-27 18:37:58',
                'updated_at' => '2017-05-27 18:37:58',
            ),
            27 => 
            array (
                'id' => 28,
                'num_factura' => 5005969,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Maria Zapata',
                'fecha_nacimiento' => '1974-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Correo y Env.TPY',
                'medico' => 'Dr, Carlos Alcerro',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            28 => 
            array (
                'id' => 29,
                'num_factura' => 5005965,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Fabiola Cruz',
                'fecha_nacimiento' => '1993-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'POLICLINICA',
                'medico' => 'Dr. Machado',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            29 => 
            array (
                'id' => 30,
                'num_factura' => 5005972,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Paola Mendoza',
                'fecha_nacimiento' => '1964-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CHOLUTECA',
                'medico' => 'Dr. Abel Aguilar',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            30 => 
            array (
                'id' => 31,
                'num_factura' => 5005970,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Vicky Palacios',
                'fecha_nacimiento' => '1965-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CL. SAN JORGE',
                'medico' => 'Dr. Sandoval',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            31 => 
            array (
                'id' => 32,
                'num_factura' => 5005967,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Manuela Sanchez',
                'fecha_nacimiento' => '1993-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'H.M.C Laboratorio',
                'medico' => 'Dr. Jose Manuel Claros',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            32 => 
            array (
                'id' => 33,
                'num_factura' => 5005966,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Keidy Elvir',
                'fecha_nacimiento' => '1993-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Correo y Env.TPY',
                'medico' => 'Dr.  Edgardo Ponce',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            33 => 
            array (
                'id' => 34,
                'num_factura' => 5005971,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Sindy Alvarez',
                'fecha_nacimiento' => '1994-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'H.M.C Laboratorio',
                'medico' => 'Dr.  Zuniga',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            34 => 
            array (
                'id' => 35,
                'num_factura' => 5005968,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Keren Izaguirre',
                'fecha_nacimiento' => '1993-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'HOSPITAL MILITAR',
                'medico' => 'Dr. Valladares',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            35 => 
            array (
                'id' => 36,
                'num_factura' => 5005981,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Fabiola Nuñez',
                'fecha_nacimiento' => '1985-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'H.M.C Laboratorio',
                'medico' => 'Dr. Aguiluz',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            36 => 
            array (
                'id' => 37,
                'num_factura' => 5005988,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Keren Izaguirre',
                'fecha_nacimiento' => '1985-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'H.M.C Laboratorio',
                'medico' => 'Dr. Victor Quintanilla',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            37 => 
            array (
                'id' => 38,
                'num_factura' => 5005980,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Fatima Guillen',
                'fecha_nacimiento' => '1985-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'MEDICENTRO',
                'medico' => 'Dr. Abril Ojeda',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            38 => 
            array (
                'id' => 39,
                'num_factura' => 5005973,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Maria Zuniga',
                'fecha_nacimiento' => '1945-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CHOLUTECA',
                'medico' => 'Dr.  Varela',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            39 => 
            array (
                'id' => 40,
                'num_factura' => 5005982,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Noel Maradiaga',
                'fecha_nacimiento' => '1942-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'H.M.C Laboratorio',
                'medico' => 'Dr. Adonis Figueroa',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            40 => 
            array (
                'id' => 41,
                'num_factura' => 5005989,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Paulina Rubio',
                'fecha_nacimiento' => '1984-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CL. SAN JORGE',
                'medico' => 'Dr. Victor Quintanilla',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            41 => 
            array (
                'id' => 42,
                'num_factura' => 5005975,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Maria Pastrana',
                'fecha_nacimiento' => '1947-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CL. SAN JORGE',
                'medico' => 'Dr.  Raul Espinoza',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            42 => 
            array (
                'id' => 43,
                'num_factura' => 5005978,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Benjamin Oyuela',
                'fecha_nacimiento' => '1985-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Correo y Env.TPY',
                'medico' => 'Dr. Adolfo Elvir',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            43 => 
            array (
                'id' => 44,
                'num_factura' => 5005987,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Flavio Hernandez',
                'fecha_nacimiento' => '1985-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Correo y Env.TPY',
                'medico' => 'Dr. Alan Araujo',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            44 => 
            array (
                'id' => 45,
                'num_factura' => 5005983,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Gloria Lopez',
                'fecha_nacimiento' => '1925-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'H.M.C Laboratorio',
                'medico' => 'Dr. Adelmo Arita',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            45 => 
            array (
                'id' => 46,
                'num_factura' => 5005984,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Gabriel Lopez',
                'fecha_nacimiento' => '1945-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'HOSPITAL MILITAR',
                'medico' => 'Dr. Adolfo Elvir',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            46 => 
            array (
                'id' => 47,
                'num_factura' => 5005985,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Fatima Morales',
                'fecha_nacimiento' => '1985-01-01 00:00:00',
                'edad' => '32 A',
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CL. SAN JORGE',
                'medico' => 'Dr. Alberto Espinoza',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:57:54',
            ),
            47 => 
            array (
                'id' => 48,
                'num_factura' => 5005977,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Kevin Zuniga',
                'fecha_nacimiento' => '1948-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CL. SAN JORGE',
                'medico' => 'Dr. Adan Mora',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            48 => 
            array (
                'id' => 49,
                'num_factura' => 5005974,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Alejandro Elvir',
                'fecha_nacimiento' => '2016-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CL. SAN JORGE',
                'medico' => 'Dr. Aaron Baruch',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-06-03 11:40:56',
                'updated_at' => '2017-06-03 11:40:56',
            ),
            49 => 
            array (
                'id' => 50,
                'num_factura' => 5005976,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Sarahi Hernandez',
                'fecha_nacimiento' => '1945-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'Ruben Dario',
                'medico' => 'Dr. Abraham Rodriguez',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:57',
                'updated_at' => '2017-06-03 11:40:57',
            ),
            50 => 
            array (
                'id' => 51,
                'num_factura' => 5005986,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Kendy Rosales',
                'fecha_nacimiento' => '1975-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CL. SAN JORGE',
                'medico' => 'Dr. Valdes',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:57',
                'updated_at' => '2017-06-03 11:40:57',
            ),
            51 => 
            array (
                'id' => 52,
                'num_factura' => 5005979,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Karen Izaguirre',
                'fecha_nacimiento' => '1994-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'HOSPITAL MILITAR',
                'medico' => 'Dr.  Raul Espinoza',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:57',
                'updated_at' => '2017-06-03 11:40:57',
            ),
            52 => 
            array (
                'id' => 53,
                'num_factura' => 5005991,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Laura Pausini',
                'fecha_nacimiento' => '1985-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'CEMED',
                'medico' => 'Dra. carias',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:57',
                'updated_at' => '2017-06-03 11:40:57',
            ),
            53 => 
            array (
                'id' => 54,
                'num_factura' => 5005990,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Sarahi Hernandez',
                'fecha_nacimiento' => '1995-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => 'H.M.C Laboratorio',
                'medico' => 'Dra. Alba Figueroa',
                'status' => 'Valida',
                'sexo' => 'F',
                'created_at' => '2017-06-03 11:40:57',
                'updated_at' => '2017-06-03 11:40:57',
            ),
            54 => 
            array (
                'id' => 55,
                'num_factura' => 5005992,
                'num_cedula' => NULL,
                'nombre_completo_cliente' => 'Cristian Castro',
                'fecha_nacimiento' => '1985-01-01 00:00:00',
                'edad' => NULL,
                'correo' => NULL,
                'correo2' => NULL,
                'direccion_entrega_sede' => NULL,
                'medico' => 'Dra. Alba Figueroa',
                'status' => 'Valida',
                'sexo' => 'M',
                'created_at' => '2017-06-03 11:40:57',
                'updated_at' => '2017-06-03 11:40:57',
            ),
        ));
        
        
    }
}